### ISSUE TITLE
TypedJson issues for release ToDo

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#2125]
Todo umbrella for issues concerning Typed json and  Puppets. 

**To fix before vacation (no info needed)**
- [ ] Reuse Json in other Jsons #2059
- [ ] Send schema and metadata for puppets to clients. #2136
- [ ] Dirtycheck in puppets needs to handle deleted dataobjects. #2140
- [x] Add unittests for testing compiled json with generated code. #1944
- [ ] Number casting in Typed JSON #2132

**Info/discussion/other needed**
- [x] Shared transaction for applications that are merged. #1753. 
  - Polyjuice apps needed that use the same datamodel to test the current implementation of shared transaction.
  - First implementation done but NOT pushed to develop yet.
- [x] Fix parent correct type information #778
  - Discussion with @starcounter-jack needed. Info in the issue.

**The rest** 
- [ ] Remove class DynamicJson from Starcounter.XSON project. #2037
- [ ] Warn or handle misspelling of Puppet eventhandlers. #2019
- [ ] Handler is called twice when client asks for both html and json. #2124
- [ ] Change all exceptions with custom messages to proper errorcodes in typedjson projects #1959
- [ ] Implement the functionality to disable the dirtycheck for specific properties or whole classes #1602 
- [x] Add compile-time error if a property in the viewmodel have the same name as an existing property. #1962
- [ ] Add verification to typedjson to avoid circle references that hangs the database. #2118
- [ ] Make a high level (managed) Faster-than-JSON tree creator #2135
- [x] Investigate and add functionality in extension for adding existing typedjson files. #2194 

**Documentation issues**
- [ ] JSON-by-example data types not documented #2066
- [ ] Unclear error message for JSON property "Input" #2065
- [ ] Difference between Json.toString() and Json.toJson() ? #772
- [ ] XSON JSON treating of null values #269
- [ ] Document JSON fields: Html, Data, HtmlContent, etc #759
- [ ] Document how Typed JSON can be used to host SQL results #689
- [ ] Documentation - Puppet reuse and inheritance #1028
- [ ] Typed JSON page should be written #839
- [ ] Update the wikipage 'Populating JSON with database data' with information about auto binding. #1782
- [ ] Create a Wiki that describes how to use our Json serializer/deserializer #501
- [ ] Support unsigned integers in typed json. #1065

**Comment by chrhol** [comment]
Really old and outdated issue. I will close this one and start over.
