### ISSUE TITLE
Sessionblobs and puppets ToDo

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Starcounter#2154]
Umbrella issue for parts that needs to be implemented to support sessionblobs and a common protocol for both typedjson/puppets and presenters (legacy applications).
- [ ] Make a high level (managed) Faster-than-JSON tree creator/reader/writer #2135
- [ ] Send schema and metadata for puppets to clients. #2136 
- [ ] Specify structure of instancetrees in puppets when serialized to blobs. #2153
