### ISSUE TITLE
Unify meta-data and their creation

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2169]
Since #1731 removed meta-data and their population outside the kernel, it is possible to have one place with all meta-data and populate them when corresponding public API functions are called.
This issue of unifying meta-data from systables project and from SQL processor includes:

- [x] Improve the schema of meta-data and materialized meta-tables might be removed by moving additional columns to the new meta-tables (#2202)
- [x] Implement the public part of the schema of meta-data in **develop**
- [x] Decide the place for all meta-data, which can be together with API wrappers (see systabels poject) or isolated into separate project (#2229, more)
- [x] Merge the implementations from systables and SQL processor by refactoring and taking good parts from both places (#2228, #2232, #2233, more)
- [x] Populate meta-data about meta-tables, includes populating meta-data about inherited columns
- [x] Create all meta-tables at the same time and remove creation from host class upgrade
- [x] Refactor different meta-data to reduce redundant meta-data descriptions (#2208, more)
- [x] Populate all meta-data from API calls and remove population from managed code
- [ ] Refactor .NET meta-data population to use stored meta-data instead of reflection
- [x] Fix correct error reporting and propagation (#2232, more)

This issue is part of #2106, #1240 and #1242.

**Comment by k-rus** [comment]
> Refactor .NET meta-data population to use stored meta-data instead of reflection

I am not sure if it will be done. If needed separate issue will be created.
Otherwise most tasks are done or separate issues exist.
