### ISSUE TITLE
Improved meta-data schema with merged materialized meta-tables

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2202]
This issue will specify changes in the meta-data schema as part of #2169.

The following tables will be removed:
- [x] `Starcounter.Internal.Metadata.HostMaterializedTable`
- [x] `materialized_table`
- [x] `materialized_column`
- [x] `materialized_index`
- [x] `materiazlied_index_column`

The following properties will be added or moved to the following meta-tables:
- [x] `table_id` from `materialized_table` to `Starcounter.Metadata.RawView`
- [x] `DbTypecode` from `Starcounter.Metadata.MapPrimitiveType` to `Starcounter.Metadata.ClrPrimitiveType`
- [x] `Mapper` or `Table` to `Starcounter.Metadata.VMView`
- [x] `IndexId` from `materialized_index` to `Starcounter.Metadata.Index`
- [x] `Nullable` to `Starcounter.Metadata.Column`
- [x] internal `Token` to `Starcounter.Matedata.RawView`
- [x] internal `Token` to `Starcounter.Metadata.Column`
- [x] internal `Token` to `Starcounter.Metadata.Index`
- [x] internal `AutoTypeInstance` to `RawView`
- [x] internal `ColumnIndex` and `AlwaysUnique` from `materialized_index_column` to `Starcounter.Metadata.Column`

The following properties will be removed from the following meta-tables:
- [x] `MaterializedColumn` from `Starcounter.Metadata.Column`
- [x] `MaterializedIndex` from `Starcounter.Metadata.Index`

The following property type changing will be done:
- [x] Property `Table` of `Starcounter.Metadata.Index` from `Starcounter.Matedata.Table` to `Starcounter.Matedata.RawView`

The following renaming will be done:
- [ ] Meta-table `Starcounter.Metadata.IndexedColumn` into `Starcounter.Metadata.ColumnIndex`
- [x] Meta-table `Starcounter.Matedata.Type` into `Starcounter.Matedata.DataType`
- [x] Property `Type` to `DataType`

The following tables will be added:
- [x] `Starcounter.Metadata.Property` with properties `Get` and `Set`
- [x] `Starcounter.Metadata.MappedProperty` with properties `Column`
- [x] `Starcounter.Metadata.StronglyTypedColumn` with property `StaticTypeName`

Inheritance changes:
- [x] `RawView` inherits `Table`
- [x] `VMView` inherits `Table`
- [x] `Property` inherits `Member`
- [x] `MappedProperty` inherits `Property`
- [x] `CodeProperty` inherits `Property`
- [x] `StronglyTypedColumn` inherits `Column`
- [ ] `Type` extends `Entity`
- [ ] `Member` extends `Entity`
- [ ] `Index` extends `Entity`
- [ ] `IndexedColumn` extends `Entity`

`Starcounter.Metadata.VMView` will be mapped to `Starcounter.Metadata.RawView`, probably, through a simple mapper class.

[The proposed version](http://scwiki.innowait.se/Graphs/metadatatablesNew.svg)

**Comment by k-rus** [comment]
To reduce name collision I suggest:
- Rename Meta-table `Starcounter.Matedata.Type` into `Starcounter.Matedata.ValueType`
- Rename Property `Type` to `ValueType`

**Comment by per-samuelsson** [comment]
> Rename Meta-table Starcounter.Matedata.Type into Starcounter.Matedata.ValueType

Isn't "data type" the common way to refer to this? DataType? Or is the type more than just data types? Can you give an example of a few instances in this table?

**Comment by k-rus** [comment]
> Rename Meta-table Starcounter.Matedata.Type into Starcounter.Matedata.ValueType
> Isn't "data type" the common way to refer to this? DataType? Or is the type more than just data types? Can you give an example of a few instances in this table?

This property is the type of a column, which can be either primitive type or a database type or a host class. The meta-table is referred by the property and its instances describe either database primitive, mapped primitive such as CLR primitive, database hard type or host class such as CLR class.

Thank you for the suggestion I will consider `DataType` as better option.

**Comment by k-rus** [comment]
Most tasks are completed. One task is decided not to do. Four tasks are done but not merged. Closing.
