### ISSUE TITLE
Fix problems in next

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2228]
Fix SqlProcessor and Level1 to use the kernel API with tokens through `systables` project. This is first step in refactoring `systables` and meta-data from `SqlProcessor`.
Related to issue #2169.

Starcounter runs with new kernel API in branch **next**. However, some parts does not work and tests are disabled and user experience is not great. Known problems:

- [ ] Fix number of indexes per table or Refactor the SQL regression test (issue #2257) or replace the SQL regression test with new framework (issues, e.g.,  #1928)
- [ ] Fix cache invalidation in implicit read transaction (issue #2249)
- [ ] Refactor meta-data creation (issues #2169, #2233) to:
  - [ ] Fix invariant identifier name (part of issue #2253)
  - [ ] store original identifier name and provide to user (part of #2253)
  - [x] populate meta-data about all meta-tables
- [ ] Fix transactions for schema update operations (issue #2248)
- [ ] If a user is required to create explicit transaction for schema update operation (option 2 in #2248), then we need to fix that the same transaction allows several schema update operations, e.g., creation of several indexes in a single transaction.
- [ ] Fix identifier name length (issue #2256)
- [ ] Allow insert into system tables in the same transaction as schema update and then make meta-table system tables
- [ ] Replace names in SQL test
- [ ] Fix reported errors, e.g., when no instance of sys_table or sys_column for given table or column cannot be found during get column or table info in systables
- [ ] Fix creation of meta-data for schema update. (see issue #2387)
- [ ] Fix Unload/Reload to run with dynamic system, which does not work as noted [here](https://github.com/Starcounter/Starcounter/issues/2477#issuecomment-70483469)

**Comment by k-rus** [comment]
next does not exist anymore. the issue is obsolete.
