### ISSUE TITLE
Merge meta-data from SqlProcessor to systables

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2233]
It is umbrella issue. Part of #2169.
Some tasks:
- [ ] Fix or replace db_exception with error codes (#2232)
- [ ] Make meta-tables to be system tables with STAR_SYSTEM_TABLE (see reply to [this comment](https://github.com/Starcounter/Starcounter/issues/2106#issuecomment-52495242))
- [ ] Remove interface method star_get_label
- [ ] Replace `wchar_t` with `ucs2_char`
- [ ] Remove materialized tables, i.e., according the new schema (#2702)
- [ ] Improve error message during meta-data initialisation, see `verify`
- [ ] Complete verifying base table
- [x] Set full name and use it instead
- [ ] Add regression test to start previously created database
- [ ] Set Unique column of raw columns
- [ ] Replace DEF file with pragma
- [ ] DDL operations to populate meta-table directly in systables project
- [ ] Set TableId for each created RawView instance (related to the previous item)
- [ ] Populate `Starcounter.Metadata.Index` and its columns and add regression tests
- [ ] Improve initialisation of meta-tables and related structures for initial creation and in the case of already created

**Comment by k-rus** [comment]
Done
