### ISSUE TITLE
Update Meta-data to reflect new version for next

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2447]
New version for next is described in #2202 

The work to do:
- `Type` extends `Entity`
- `Member` extends `Entity`
-  `Index` extends `Entity`
- `IndexedColumn` extends `Entity`
- [x] Move property `DbTypeCode` from `MapPrimitiveType` to `ClrPrimitiveType`
- [x]  Remove `HostMaterialiedTable`
- [x] Move property `MaterializedTable` from `HostMaterialiedTable` to `RawView`
- [x] Add property `Mapper` to `VMView`
- [x] Add property `Inherited` to `Member`
- [x] Add `Property` extending `Member`
- [x] `CodeProperty` extends `Property`
- [x] Add `MappedProperty` extending `Property`
-  Add property `Nullable` to `Column`
-  Add `RawColumn` extending `Column`
-  Move property `MaterializedColumn` from `Column` to `RawColumn`
-  Refer property `Table` of `Index` to `RawView`
- Add property `IndexId` to `Index`

[The updated schema](http://scwiki.innowait.se/Graphs/metadatatables.svg)
[The updated public schema](http://scwiki.innowait.se/Graphs/metadatapublic.svg)

**Comment by k-rus** [comment]
> Moving out MaterializedTable from ClrClass requires to fix reload/unload.

The easiest fix is to returned `MaterializedTable` back to `VMView`, i.e., like `HostMaterializedTable` presented. This way I think to go, which requires to remove `MaterializedTable` from `VMView` later during refactoring.

**Comment by k-rus** [comment]
> Moving out MaterializedTable from ClrClass requires to fix reload/unload.
> The easiest fix is to returned MaterializedTable back to VMView, i.e., like HostMaterializedTable presented. This way I think to go, which requires to remove MaterializedTable from VMView later during refactoring.

The refactoring is not considering INSERT INTO implementation directly, therefore I will do more proper solution.

**Comment by k-rus** [comment]
There will be no more changes in meta-data schema in branch `develop` due to difficulty of doing merge with `next`. The state is updated in the main post and in the graphs, so graphs reflect the current state. This issue is closed. The work continues in branch `next`, see issue #2202.
