### ISSUE TITLE
Implement meta-data versioning in database server

### ISSUE THREAD

**Issue by k-rus** [Starcounter/Starcounter#2550]
If meta-data schema changes then the database image can be incompatible with new version of meta-data, i.e., Starcounter. To notify the user with correct message it is necessary to keep information about meta-data version together with database image, i.e., in the server folder. The easiest way is to extend configuration file with meta-data version value and implement an accessor method in Level1 to read the version.

If no other suggestion will come, the tasks in the issue are:
- [ ] Extend Level1 with meta-data version
- [ ] Add meta-data version to installation package from Level1
- [ ] Extend server configuration with meta-data version
- [ ] Add API to Level1 to read meta-data version from the installation
- [ ] Add API to Level1 to read meta-data version from the server configuration

This is needed to implement informative error messages in #2487 and #2495 and to implement notification in installer, #2496.

**Comment by dan31** [comment]
Related and quite long discussion there https://github.com/Starcounter/CompanyTrack/issues/138.

**Comment by k-rus** [comment]
The actual implementation was decided and necessary work was done in the metalayer.

Archiving.
