### ISSUE TITLE
Roadmap to Polymer 1.1

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2854]
This is an umbrella issue to discuss the process of upgrading all our Web Components and sample apps to Polymer 1.1.

Deadline: 1 October 2015

## Milestone 1 - Proof of concept
- [x] [Create dom-bind-notifier to sync template with JS object](https://github.com/Juicy/dom-bind-notifier) (@tomalec)
- [x] [Create SysUpgrade repo with static files for Polymer 1.1](https://github.com/Polyjuice/SysUpgrade) (@tomalec)
- [ ] Create puppet-dom-bind-notifier (@tomalec)
- [x] [InvoiceDemo: Migrate to Polymer 1.1](https://github.com/Starcounter/InvoiceDemo/issues/24)  (@tomalec)
- [x] Upgrade imported-template (@tomalec)
- [x] Upgrade starcounter-include (@tomalec)

## Milestone 2 - Upgrade Custom Elements

Upgrade Custom Elements from Polymer 0.5 to Polymer 1.1 or **(preferably) plain Web Components**

- [x] [juicy-tile-list](https://github.com/Juicy/juicy-tile-list/issues/43) (@miyconst) - vanilla component
- [x] [juicy-tile-grid](https://github.com/Juicy/juicy-tile-grid/issues/25) (@miyconst) - vanilla component, but demos still use Polymer 1.1
- [x] [juicy-color-picker](https://github.com/Juicy/juicy-color-picker/issues/2) (@miyconst) - vanilla
- [x] juicy-border-picker (@miyconst) - polymer 1.1
- [x] juicy-tile-editor-form (@miyconst) - polymer 1.1
- [x] juicy-tile-tree (@miyconst) - vanilla
- [x] juicy-toggle-icon-button (@miyconst) - polymer 1.1
- [x] [juicy-tile-editor](https://github.com/Juicy/juicy-tile-editor/issues/84) (@miyconst) - polymer 1.1
- [x] [juicy-tiles-setup-sync](https://github.com/Juicy/juicy-tiles-setup-sync/issues/1) (@miyconst) - polymer 1.1, also added property `use-local-storage` to save value with `iron-localstorage`
- [x] Launcher/starcounter-include (@tomalec)
- [x] launcher-launchpad (@miyconst) - polymer 1.1, the server side also reworked a bit, not applications should include `html` property in the `AppName.json` which should point to icon's html template
- [x] launcher-main (@miyconst) - polymer 1.1
- [x] launcher-menu (@miyconst) - polymer 1.1
- [x] launcher-search-input (@miyconst)
- [x] [hot-table](https://github.com/handsontable/hot-table/issues/16) (@budnix)

## Milestone 3 - Upgrade the sample apps

- [x] AppStoreClient
- [x] Barcodes
- [x] Chatter
- [x] GoogleSignIn
- [x] Images
- [x] Launcher
- [x] People
- [x] Procurement
- [x] Products
- [x] SignIn
- [x] Skyper
- [x] UsageTracker
- [ ] UserAdmin
- [x] Welcome

(@miyconst, @tomalec, @warpech)

**Comment by warpech** [comment]
I created a blog post: http://starcounter.io/nightly-changes/roadmap-to-polymer-1-1/

Any comments?

**Comment by warpech** [comment]
@miyconst could you provide a list of custom elements and apps for milestones 2 & 3?

**Comment by miyconst** [comment]
Added list of components to start upgrading, other will add later, if found any.

**Comment by warpech** [comment]
Added hot-table to the list. Added responsible persons to the work items

**Comment by warpech** [comment]
Added a link to juicy-tile-list and marked hot-table as done

**Comment by tomalec** [comment]
WDYT about upgrading juicy.gihub.io to Polymer 1.1? 8 of 19, including most crucial elements are already Polymer 1.1 ready:
`juicy-tile-list`, `juicy-tile-grid`, `dom-bind-notifier`, `juicy-html` + less importand ones `juicy-ace-editor`, `juicy-markdown`, `juicy-markdown-editor`, `juicy-filedrop`

It would simplify branching flow, demo pages, etc.

**Comment by miyconst** [comment]
`juicy-tile-grid` is not ready yet.

**Comment by tomalec** [comment]
ah, sorry, then 7/19

**Comment by warpech** [comment]
@tomalec, can you update Milestone 1 part in the OP?
@miyconst, can you update Milestone 2?

**Comment by miyconst** [comment]
I have finished or almost finished many of the elements, but they all are in the separate branch, and don't yet fully work all together in Launcher.

Should I mark it as done?

**Comment by warpech** [comment]
I suggest merging to master and then marking it as done. You can even issue a prerelease if that helps (like @tomalec did with https://github.com/Juicy/juicy-html)

**Comment by miyconst** [comment]
Okay. Will do that tomorrow.

**Comment by tomalec** [comment]
I'd like to mark them as done, once I'll release a version, and I'd like to do that once I will check they work together in Launcher not only at demo pages

**Comment by miyconst** [comment]
Updated set of migrated/vanillazed components.

**Comment by miyconst** [comment]
Inserted list of Polyjuice apps to migrate.

**Comment by tomalec** [comment]
I'm affraid I will not make puppet-dom-bind notifier by this time, but I think it should not be a problem because we already have regular dom-bind-notifier, and the future migration should be seamless

**Comment by warpech** [comment]
Np. but we need to release it anyway tomorrow, so please concentrate on explaining the changes on starcounter.io and updating the docs.

**Comment by warpech** [comment]
We will release Polymer 1.1-compatible upgrade tomorrow according to the plan. Most of the sample apps are already migrated.

**Comment by Starcounter-Jack** [comment]
Cool. I am so happy that we are now going sharp with webcomponents/polymer on an official version.

**Comment by warpech** [comment]
Implementation of `puppet-dom-bind notifier` is now tracked in #2922

**Comment by warpech** [comment]
All of the apps now migrated. They require Starcounter 2.1.x, which is the first version compatible with Polymer 1.1 (see [blog post](http://starcounter.io/nightly-changes/starcounter-2-1-now-compatible-with-polymer-1-1/))

Polymer 1.1 is up to date on https://github.com/juicy/juicy.github.io as well.

Remaining tasks: 
- Implementation of puppet-dom-bind-notifier still undergoing (#2922).
- Release UserAdmin app (https://github.com/StarcounterSamples/UserAdmin/issues/8)

Closing as done, thanks everyone! :tulip:
