### ISSUE TITLE
Umbrella: Server side enhancement

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3039]
This is an umbrella issue for server side improvements, which I would like to see before the Indian trip

- [x] [Simplification to OntologyMap method](https://github.com/Starcounter/Starcounter/issues/3036)
- [ ] [Enhancement to Handle.GET method](https://github.com/Starcounter/Starcounter/issues/3038)
- [ ] [Ambiguous Handle name](https://github.com/Starcounter/Starcounter/issues/2733)
- [ ] [Default constructor for Starcounter.Session](https://github.com/Starcounter/Starcounter/issues/2966)
- [ ] [Add a Visual Studio template for creating pages, not just JSON](https://github.com/Starcounter/Starcounter/issues/2931)
- [ ] [Transaction.Rollback: The operation failed because of an invalid object access](https://github.com/Starcounter/Starcounter/issues/2814)

Related issues:

- [x] [Replace AddFilterToMiddleware with AddRequestFilter](https://github.com/Starcounter/Starcounter/issues/2969)
- [ ] [Thoughts on Handle.X methods](https://github.com/Starcounter/Starcounter/issues/2970)
- [ ] [Mapping flexibility](https://github.com/Starcounter/Starcounter/issues/2930)

cc @warpech, @dan31, @alemoi

**Comment by per-samuelsson** [comment]
Really good initiative, @miyconst. I wish I was at a point where I was more fluent on how these parts worked today, so I could give more/better feedback. Will still try in micro-contexts where ever I can.

**Comment by warpech** [comment]
Are there any "must haves" here in your opinion? Or are they all "nice to haves"? This will help to prioritize.

**Comment by miyconst** [comment]
Very important issue, I would say "must have":
[Transaction.Rollback: The operation failed because of an invalid object access](https://github.com/Starcounter/Starcounter/issues/2814)

I would really like to see fixed:
[Ambiguous Handle name](https://github.com/Starcounter/Starcounter/issues/2733)

**Comment by miyconst** [comment]
I close this issue as too old.
