### ISSUE TITLE
Layout editor sessions

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3237]
This is a discussion issue for morning (11:30 - 11:45) sessions of layout editor with Douglas.

The dedicated playground: 
http://douglas-11.mysampleapp.com/

The installed apps:
- [x] Products
- [x] Images
- [ ] Barcodes
- [ ] Procurement

cc @Starcounter-Jack, @dan31, @tomalec, @warpech

**Comment by miyconst** [comment]
#### Tasks for the first sessions (2016.01.12):

- [ ] 1. Make image 100x100 in size.
- [ ] 2. Put all three buttons in a row.
- [ ] 3. Put the buttons in a group with a gutter of 10.
- [ ] 4. Move the image on top of the button.
- [ ] 5. Hide navigation buttons, Barcode section, Suppliers section, and Image label.
- [ ] 6. Set label width to 15%.
- [ ] 7. Set input width to 85%.
- [ ] 8. Make buttons group as tight.
- [ ] 9. Put each label-input pair into a group.
- [ ] 10. Put label-input groups, image, buttons group into a group with a gutter of 10.
- [ ] 11. Put label-input groups into a group with a gutter of 10.
- [ ] 12. Put the image to the right side of the inputs.

I am not sure how fast we will proceed, so I have created many tasks to make sure to cover all the time.

**Comment by miyconst** [comment]
#### Tasks for 2016.01.20 session:

The first version of `juicy-tile-simple-editor` is done and ready for testing here:
http://juicy.github.io/juicy-tile-editor/simple.html

On the demo page I have faked response from Products, Images, Barcodes applications.

- [ ] 1. Put Save & Cancel button to the very bottom.
- [ ] 2. Put Barcode value section under Description.
- [ ] 3. Hide Image label.
- [ ] 4. Put Image and Barcode in one line.
- [ ] 5. Put Supplier Name & Price sections on one line.

**Comment by miyconst** [comment]
Closing the issue as no longer needed.
